- name: Launch the database container
  docker_container:
    name: database
    image: azorus/tp-devops-database:latest
    networks:
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
