all:
  vars: # Variables communes pour tous les serveurs
    ansible_user: centos
    ansible_ssh_private_key_file: /home/paul/.ssh/id_rsa # Chemin vers la clé privée SSH
  children:
    prod: # Groupe 'prod' pour les serveurs de production
      hosts: paul.velter.takima.cloud # Liste des hôtes pour le groupe 'prod'