name: CI devops 2023 # Nom du workflow
on: # Événements déclencheurs du workflow
  push: # Déclenché lors d'un push
    branches: # Spécifie les branches concernées
      - main # Déclencher pour la branche principale
  pull_request:

jobs: # Définition des jobs
  test-backend: # Job pour les tests du backend
    runs-on: ubuntu-22.04 # Système d'exploitation pour l'exécution

    steps: # Étapes à exécuter
      - uses: actions/checkout@v2.5.0 # Cloner le code depuis GitHub

      - name: Set up JDK 17 # Configuration du JDK 17
        uses: actions/setup-java@v3 # Utilisation de l'action setup-java
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and test with Maven # Construction et test avec Maven
        # Commande pour exécuter Maven avec les objectifs de build et de test, ainsi que l'analyse avec SonarQube
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=paul-velt_tp-devops -Dsonar.organization=paul-velt -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./Backend/pom.xml

  build-and-push-docker-image: # Job pour construire et pousser les images Docker
    needs: test-backend # Dépendance du job 'test-backend'
    runs-on: ubuntu-22.04 # Système d'exploitation pour l'exécution

    steps: # Étapes à exécuter
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} # Commande de connexion à DockerHub

      - name: Checkout code # Cloner le code depuis GitHub
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend # Construction et poussée de l'image backend
        uses: docker/build-push-action@v3  # Utilisation de l'action build-push-action
        with:
          context: ./Backend # Chemin relatif du code source avec Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-backend:latest # Tags pour l'image backend
          push: ${{ github.ref == 'refs/heads/main' }} # Pousser uniquement si la branche est main

      - name: Build image and push database # Construction et poussée de l'image database
        uses: docker/build-push-action@v3
        with:
          context: ./Database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd # Construction et poussée de l'image httpd
        uses: docker/build-push-action@v3
        with:
          context: ./Frontend/HTML
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}


